### ISSUE TITLE
autoquilt: command not found

### ISSUE THREAD

**Issue by MajaKL** [ubuntor/autoquilt#1]
We are two students interested in working with your code for our thesis. We have run the build instructions, but we run into issues when running the code for usage, we get the error: 'autoquilt: command not found'. Where are you supposed to run the "autoquilt [image] [FDoG image from flowabs] [output pattern file]" command? Or do you know what else might cause the problem?
We were unsure how to ask this of you, but would greatly appreciate it if you could help. If you would rather answer through e-mail, my e-mail is: keml@itu.dk

**Comment by ubuntor** [comment]
oops, that should be `./autoquilt`, which should have been generated if it built correctly.

**Comment by MajaKL** [comment]
Hi, thanks for the help, it worked!
